"""Statistical significance tests for backtest results.

Monte Carlo Permutation Test
----------------------------
Tests whether the strategy's Sharpe ratio is statistically significant
by comparing it to a null distribution generated by randomly shuffling
the actual return series.

Methodology:
    1. Run the strategy on the original bar sequence -> actual_sharpe
    2. For each of N permutations:
       a. Shuffle the bar RETURN sequence (preserving open/close structure)
       b. Re-run the strategy on the shuffled bars
       c. Record permuted_sharpe
    3. p_value = fraction of permuted_sharpe >= actual_sharpe
    4. Reject null (strategy has no skill) if p_value < alpha (0.05)

Why permute returns (not signals)?
    Permuting returns changes the transition matrix seen by the Markov
    model, which changes the signals themselves. This correctly tests
    whether the Markov autocorrelation structure -- not just the signals --
    is responsible for the strategy's performance.

Usage::

    from src.backtest.statistical_tests import monte_carlo_permutation, PermResult
    result = monte_carlo_permutation(
        bars=bars,
        config=config,
        n_perms=10000,
        seed=42,
    )
    print(f"p-value: {result.p_value:.4f}, significant: {result.significant}")
"""

from __future__ import annotations

import copy
import time
from dataclasses import dataclass
from typing import List, Optional

import numpy as np

from src.backtest.bar_replay import BacktestConfig, BarReplay, OhlcBar
from src.backtest.metrics import BacktestMetrics, compute_metrics
from src.logger import get_logger

logger = get_logger("statistical_tests")


@dataclass
class PermResult:
    """Result of a Monte Carlo permutation test."""
    actual_sharpe: float
    perm_sharpes: np.ndarray   # shape (n_perms,)
    p_value: float
    significant: bool          # True if p_value < alpha
    alpha: float               # significance threshold (default 0.05)
    n_perms: int
    elapsed_s: float

    @property
    def perm_sharpe_mean(self) -> float:
        return float(np.mean(self.perm_sharpes))

    @property
    def perm_sharpe_std(self) -> float:
        return float(np.std(self.perm_sharpes))

    @property
    def perm_sharpe_p95(self) -> float:
        return float(np.percentile(self.perm_sharpes, 95))

    def summary_table(self) -> str:
        lines = [
            "| Statistic | Value |",
            "|-----------|-------|",
            f"| Actual Sharpe | {self.actual_sharpe:.4f} |",
            f"| Perm mean Sharpe | {self.perm_sharpe_mean:.4f} |",
            f"| Perm std Sharpe | {self.perm_sharpe_std:.4f} |",
            f"| Perm 95th pctile | {self.perm_sharpe_p95:.4f} |",
            f"| p-value | {self.p_value:.4f} |",
            f"| Significant (p<{self.alpha}) | {'YES' if self.significant else 'NO'} |",
            f"| N permutations | {self.n_perms} |",
            f"| Elapsed | {self.elapsed_s:.1f}s |",
        ]
        return "\n".join(lines)


def monte_carlo_permutation(
    bars: List[OhlcBar],
    config: BacktestConfig,
    n_perms: int = 10000,
    seed: int = 42,
    alpha: float = 0.05,
    nav_start: float = 100.0,
) -> PermResult:
    """Run a Monte Carlo permutation test on the strategy.

    Args:
        bars:      Historical bars (original sequence), oldest-first.
        config:    Backtest configuration.
        n_perms:   Number of permutations (10000 for production, 500 for unit tests).
        seed:      Random seed for reproducibility.
        alpha:     Significance threshold (default 0.05).
        nav_start: Starting NAV for return calculation.

    Returns:
        PermResult with p-value and permuted Sharpe distribution.
    """
    t_start = time.perf_counter()
    rng = np.random.default_rng(seed)

    # 1. Actual strategy run
    replay = BarReplay()
    actual_trades, actual_equity = replay.run(bars, config)
    actual_metrics = compute_metrics(
        actual_trades, actual_equity, n_bars=len(bars),
        bar_type=config.bar_type, nav_start=nav_start,
    )
    actual_sharpe = actual_metrics.sharpe_ratio

    logger.info(
        "PermTest: actual strategy complete",
        extra={"sharpe": round(actual_sharpe, 4), "n_trades": len(actual_trades)},
    )

    # 2. Build permuted bar sets by shuffling the RETURNS (open-to-close moves)
    #    Strategy: for each bar, keep the `open` of the original, but shuffle
    #    the actual (close - open) returns across bar positions.
    #    This preserves the price level structure while destroying autocorrelation.
    returns = _extract_returns(bars)
    perm_sharpes = np.zeros(n_perms)

    log_interval = max(1, n_perms // 10)
    for p in range(n_perms):
        shuffled_returns = rng.permutation(returns)
        perm_bars = _apply_shuffled_returns(bars, shuffled_returns)

        # Use faster settings for permutation runs
        fast_config = copy.copy(config)
        fast_config.fast_mode = True   # Markov-only (skip expensive MH)
        fast_config.seed = None

        perm_trades, perm_equity = replay.run(perm_bars, fast_config)
        perm_metrics = compute_metrics(
            perm_trades, perm_equity, n_bars=len(perm_bars),
            bar_type=config.bar_type, nav_start=nav_start,
        )
        perm_sharpes[p] = perm_metrics.sharpe_ratio

        if (p + 1) % log_interval == 0:
            elapsed = time.perf_counter() - t_start
            logger.debug(
                f"PermTest: {p+1}/{n_perms} perms done",
                extra={"elapsed_s": round(elapsed, 1)},
            )

    # 3. Compute p-value
    p_value = float(np.mean(perm_sharpes >= actual_sharpe))
    significant = p_value < alpha
    elapsed_s = time.perf_counter() - t_start

    logger.info(
        "PermTest: complete",
        extra={
            "actual_sharpe": round(actual_sharpe, 4),
            "p_value": round(p_value, 4),
            "significant": significant,
            "elapsed_s": round(elapsed_s, 1),
        },
    )

    return PermResult(
        actual_sharpe=actual_sharpe,
        perm_sharpes=perm_sharpes,
        p_value=p_value,
        significant=significant,
        alpha=alpha,
        n_perms=n_perms,
        elapsed_s=elapsed_s,
    )


def walk_forward_split(
    bars: List[OhlcBar],
    train_ratio: float = 0.75,
) -> tuple:
    """Split bars into in-sample and out-of-sample portions.

    Args:
        bars:        Full bar list, oldest-first.
        train_ratio: Fraction for in-sample (default 0.75 = 75%).

    Returns:
        (in_sample_bars, oos_bars)
    """
    n = len(bars)
    split_idx = int(n * train_ratio)
    return bars[:split_idx], bars[split_idx:]


# ── Internal helpers ──────────────────────────────────────────────────────────

def _extract_returns(bars: List[OhlcBar]) -> np.ndarray:
    """Extract open-to-close return fractions from each bar."""
    returns = []
    for b in bars:
        if b.open > 0:
            returns.append((b.close - b.open) / b.open)
        else:
            returns.append(0.0)
    return np.array(returns)


def _apply_shuffled_returns(
    original_bars: List[OhlcBar],
    shuffled_returns: np.ndarray,
) -> List[OhlcBar]:
    """Create a new bar list where each bar's close is reconstructed
    from its original open + a shuffled return.

    This preserves the open price sequence (price level) while
    destroying the temporal autocorrelation of the return series.
    """
    new_bars = []
    for i, bar in enumerate(original_bars):
        ret = float(shuffled_returns[i])
        new_close = bar.open * (1.0 + ret)
        new_bar = OhlcBar(
            symbol=bar.symbol,
            time=bar.time,
            open=bar.open,
            high=max(bar.open, new_close),
            low=min(bar.open, new_close),
            close=new_close,
            volume=bar.volume,
        )
        new_bars.append(new_bar)
    return new_bars
